version: '3.8'

services:
  django:
    build:
      context: ./backend
    container_name: django
    command: ./wait-for-it.sh mysql_brochant:3306 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    env_file:
      - ./backend/.env
    networks:
      - default

  react:
    build:
      context: ./frontend
    container_name: react
    ports:
      - "3000:3000"
    depends_on:
      - django
    env_file:
      - ./frontend/.env
    networks:
      - default

  mysql:
    image: mysql:8.4.3
    container_name: mysql_brochant
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cours_collabortif
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_django_react
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: example
    ports:
      - "8082:80"
    depends_on:
      - mysql
    networks:
      - default

volumes:
  mysql_data:
